Extract nodenv-package-json-file

diff --git a/libexec/nodenv-package-json b/libexec/nodenv-package-json
--- a/libexec/nodenv-package-json
+++ b/libexec/nodenv-package-json
@@ -14,20 +14,24 @@ abort() {
   exit 1
 }
 
-find_package_json() {
-  local package_json root="$1"
-  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
-    package_json="$root/package.json"
+READLINK=$(type -p greadlink readlink | head -1)
+[ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"
 
-    if [ -f "$package_json" ] && [ -s "$package_json" ]; then
-      echo "$package_json"
-      return 0
-    fi
-    [ -n "$root" ] || break
-    root="${root%/*}"
+abs_dirname() {
+  local cwd="$PWD"
+  local path="$1"
+
+  while [ -n "$path" ]; do
+    cd "${path%/*}"
+    local name="${path##*/}"
+    path="$($READLINK "$name" || true)"
   done
-  return 1
+
+  pwd
+  cd "$cwd"
 }
+
+bin_path="$(abs_dirname "$0")"
 
 extract_expression() {
   version_regex='\["engines","node"\][[:space:]]*"([^"]*)"'
@@ -69,11 +73,12 @@ matching_version() {
   fi
 }
 
-if ! package_json="$(find_package_json "$NODENV_DIR")"; then
+
+if ! NODENV_PACKAGE_JSON_FILE="$("$bin_path/nodenv-package-json-file")"; then
   abort "no package.json found for this directory"
 fi
 
-if ! version_spec="$(extract_expression <"$package_json")"; then
+if ! version_spec="$(extract_expression <"$NODENV_PACKAGE_JSON_FILE")"; then
   abort "no engine version configured for this package"
 fi
 
